"""empty message

Revision ID: 019f79d26c6a
Revises: 
Create Date: 2025-02-23 12:49:44.169524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019f79d26c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('atmosphere', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_ratings', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('place_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_column('place_id')
        batch_op.drop_column('address')
        batch_op.drop_column('price_level')
        batch_op.drop_column('total_ratings')
        batch_op.drop_column('rating')
        batch_op.drop_column('budget')
        batch_op.drop_column('atmosphere')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
