"""empty message

Revision ID: e2cc522e5847
Revises: 
Create Date: 2025-02-24 12:16:18.485322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cc522e5847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('restaurant_name', sa.String(length=200), nullable=True),
    sa.Column('cuisine', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('dietary', sa.String(length=100), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('atmosphere', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('place_id', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('maps_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    # ### end Alembic commands ###
